---
version: '3.7'

x-systemd:
  &default-systemd-service
  tty: true
  environment:
    - container=docker
  security_opt:
    - seccomp=unconfined
  cap_add:
    - CAP_SYS_PTRACE
    - CAP_IPC_LOCK
  ulimits:
    core:
      soft: -1
      hard: -1
    nofile:
      soft: '120000'
      hard: '120000'
  tmpfs:
    - /run
    - /run/lock
  volumes:
    - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  env_file:
    - ./envfile
  environment:
    - P4D_VERSION=${P4D_VERSION:-2020.1}
    - DOCKER_REPO=${DOCKER_REPO:-$USER}
  networks:
    - p4net

services:
  perforce:
    <<: *default-systemd-service
    image: ${DOCKER_REPO:-$USER}/perforce-server:${P4D_VERSION}
    container_name: perforce
    hostname: perforce
    volumes:
      - p4depot:/data
    ports:
      - "1666:1666"

  swarm:
    <<: *default-systemd-service
    image: ${DOCKER_REPO:-$USER}/perforce-swarm:${P4D_VERSION}
    container_name: swarm
    hostname: swarm
    depends_on:
      - perforce
    ports:
      - "8080:80"
      - "1443:443"
    environment:
      - P4PORT=perforce:1666

volumes:
  p4depot:
    external: true

networks:
  p4net:
    external: true
# vim: sts=2:ts=2:sw=2:et:ft=yaml:
