---
version: '2'
services:
  perforce:
    image: ambakshi/perforce-server
    hostname: perforce
    volumes:
      - p4depot:/data
    ports:
      - "1666:1666"
    env_file:
      - ./envfile
      
  p4swarm:
    image: ambakshi/perforce-swarm
    hostname: p4swarm
    ports:
      - "5320:80"
      - "5231:443"
    environment:
      - NAME=swarm
    volumes:
      - gfp4depot:/data

volumes:
  p4depot:
    external: true
  gfp4depot:
    external: true

# vim: sts=2:ts=2:sw=2:et:ft=yaml:
